version: "3.9"

services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zabda@2021jaya
      MYSQL_DATABASE: jayadb
      MYSQL_USER: newuser
      MYSQL_PASSWORD: Zabda@2021jaya
    networks:
      - alinet

  myapp:
    build: ./python/
    command: sh -c "sleep 10s;python3 ./bookstoreapi.py"
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - alinet

networks:
  alinet: